---
# Akash SDL - SSL Proxy (Pingap)
#
# Pingap-based SSL termination proxy with Cloudflare Origin Certificate.
# Uses static TLS cert (no ACME) - more reliable than DNS-01 challenges.
# Built on Cloudflare's Pingora framework for high performance.
#
# This proxy handles SSL for all AlternateFutures services.
# Backend services should be deployed separately and referenced by their
# Akash ingress URLs in pingap.toml.
#
# Required env:
#   - PINGAP_TLS_CERT: Cloudflare Origin Certificate (PEM)
#   - PINGAP_TLS_KEY: Private key (PEM)
#
# SSL Mode: Cloudflare Full (Strict) - end-to-end encryption

version: "2.0"

services:
  ssl-proxy:
    image: ghcr.io/alternatefutures/infrastructure-proxy-pingap:main
    expose:
      # HTTPS traffic
      - port: 443
        as: 443
        to:
          - global: true
        accept:
          - alternatefutures.ai
          - auth.alternatefutures.ai
          - api.alternatefutures.ai
          - app.alternatefutures.ai
          - docs.alternatefutures.ai
      # Health check endpoint
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      # Cloudflare Origin Certificate and Private Key
      # These are written to files by entrypoint.sh
      - PINGAP_TLS_CERT=${PINGAP_TLS_CERT}
      - PINGAP_TLS_KEY=${PINGAP_TLS_KEY}

profiles:
  compute:
    ssl-proxy:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 512Mi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        ssl-proxy:
          denom: uakt
          amount: 1000

deployment:
  ssl-proxy:
    akash:
      profile: ssl-proxy
      count: 1
