---
# Akash SDL - Dynamic SSL Proxy (Pingap + etcd)
#
# Multi-container deployment with dynamic routing configuration.
# Pingap reads configuration from etcd and hot-reloads within 10 seconds.
# No proxy restart required when adding new routes.
#
# Components:
#   - etcd: Configuration storage for dynamic routing
#   - ssl-proxy: Pingap reverse proxy with etcd backend
#
# This proxy handles SSL termination for all AlternateFutures services
# and customer sites. Routes are managed via service-cloud-api.
#
# Required env:
#   - PINGAP_TLS_CERT: Cloudflare Origin Certificate (PEM)
#   - PINGAP_TLS_KEY: Private key (PEM)
#   - ETCD_ROOT_PASSWORD: etcd authentication password
#
# SSL Mode: Cloudflare Full (Strict) - end-to-end encryption
#
# ============================================================================
# DEPLOYMENT UPDATE RULES
# ============================================================================
#
# MANIFEST-ONLY UPDATE (same dseq, same ingress URL, no DNS change):
#   Use `akash tx deployment update` or send-manifest API
#   - Environment variable changes (env section)
#   - Docker image tag changes (e.g., :latest → :v1.2.3)
#   - Command/args changes
#   - Container entrypoint changes
#   NOTE: Resources (CPU, memory, storage) must remain IDENTICAL
#
# FULL REDEPLOY REQUIRED (new dseq, NEW ingress URL, DNS update needed):
#   Must close old deployment and create new one
#   - CPU units changes
#   - Memory size changes
#   - Storage size changes
#   - Adding/removing services
#   - Changing exposed ports
#   - Changing service names
#   - Changing placement/provider attributes
#
# After full redeploy, update DNS:
#   1. Get new ingress URL from `akash query market lease-status`
#   2. Update Cloudflare CNAME: secrets.alternatefutures.ai → new-ingress.provider.com
#   3. Close old deployment to stop billing
#
# ============================================================================

version: "2.0"

services:
  # etcd - Configuration storage for dynamic routing
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    expose:
      # Client port - accessible to ssl-proxy
      - port: 2379
        as: 2379
        to:
          - service: ssl-proxy
      # Peer port - internal clustering (not used in single-node setup)
      - port: 2380
        as: 2380
        to:
          - service: etcd
    env:
      - ETCD_NAME=etcd0
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=af-proxy-cluster
    args:
      - /usr/local/bin/etcd

  # ssl-proxy - Pingap reverse proxy with etcd backend
  ssl-proxy:
    image: ghcr.io/alternatefutures/infrastructure-proxy-pingap:etcd
    expose:
      # HTTPS traffic - accepts wildcard domains for customer sites
      - port: 443
        as: 443
        to:
          - global: true
        accept:
          # Core AlternateFutures services
          - alternatefutures.ai
          - auth.alternatefutures.ai
          - api.alternatefutures.ai
          - app.alternatefutures.ai
          - docs.alternatefutures.ai
          - secrets.alternatefutures.ai
          # Function endpoints
          - "*.fn.alternatefutures.ai"
          # Customer domains (wildcards for common TLDs)
          - "*.com"
          - "*.io"
          - "*.dev"
          - "*.ai"
          - "*.xyz"
          - "*.app"
          - "*.co"
          - "*.net"
          - "*.org"
      # Health check endpoint
      - port: 8080
        as: 8080
        to:
          - global: true
      # Admin interface (internal only)
      - port: 3018
        as: 3018
        to:
          - service: ssl-proxy
    env:
      # etcd connection
      - PINGAP_ETCD_ADDR=http://etcd:2379
      - PINGAP_ETCD_PREFIX=/pingap/config
      # Cloudflare Origin Certificate and Private Key
      - PINGAP_TLS_CERT=${PINGAP_TLS_CERT}
      - PINGAP_TLS_KEY=${PINGAP_TLS_KEY}
      # Admin interface
      - PINGAP_ADMIN_ADDR=0.0.0.0:3018
    depends_on:
      - service: etcd

profiles:
  compute:
    etcd:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 2Gi
            name: etcd-data

    ssl-proxy:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 512Mi

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        etcd:
          denom: uakt
          amount: 1000
        ssl-proxy:
          denom: uakt
          amount: 1000

deployment:
  etcd:
    akash:
      profile: etcd
      count: 1
  ssl-proxy:
    akash:
      profile: ssl-proxy
      count: 1
